name: APK Builder Test

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run with debugging enabled'
        required: false
        default: false

env:
  TZ: Asia/Shanghai
  FRP_VER: 0.57.0
  GIT_URL: https://github.com/JasonKhew96/bstarTweaks

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Clone App Git
      run: |
        git clone "$GIT-URL" APK

    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

#    - name: Grant execute permission for gradlew
#      run: chmod +x gradlew

#    - name: Build with Gradle
#      run: ./gradlew build

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo timedatectl set-timezone "$TZ"

    - name: Relay SSH
#      if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
      run: |
        wget https://raw.githubusercontent.com/WLWolf5/new/master/frp/shadow
        sudo sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
        sudo cp -f shadow /etc/shadow
        rm -rf shadow
        
    - name: Run Frp
#      if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
      run: |
        curl -L https://github.com/fatedier/frp/releases/download/v0.57.0/frp_0.57.0_linux_amd64.tar.gz -o frp.tar.gz
        tar -xzf frp.tar.gz
        cp -f frp_0.57.0_linux_amd64/frpc frp
        cd frp
        chmod +x frpc
        ./frpc -c frpc2.ini
        
#    - name: if failure
#      if: ${{ failure() }}
#      run: |
        
