name: Show PWD

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 400

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Show PWD
      run: |
        pwd
        ls

    - name: Try to extract
      run: |
        7z x qsdk-12.5-k5.4.7z -m0=LZMA2 -mmt=on
