name: SSH Test

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 400

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Show PWD
      run: |
        pwd
        ls
        apt update

    - name: Setup tmate session
      uses: mxschmitt/action-tmate@master
      if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
