name: SSH Relay Test

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run with debugging enabled'
        required: false
        default: false

env:
  TZ: Asia/Shanghai
  FRP_VER: 0.57.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@main
      
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo timedatectl set-timezone "$TZ"

    - name: Relay SSH
#      if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
      run: |
        wget https://raw.githubusercontent.com/WLWolf5/new/master/frp/shadow
        sudo sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
        sudo cp -f shadow /etc/shadow
        rm -rf shadow
        
    - name: Run Frp
#      if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
      run: |
        curl -LO "https://raw.githubusercontent.com/WLWolf5/new/master/frp/frpc"
        #curl -LO "http://hk-5.lcf.im:44265/frpc.toml"
        chmod +x frpc
        ./frpc -c frpc2.ini
        
#    - name: if failure
#      if: ${{ failure() }}
#      run: |
        
    
