name: Compile With SSH

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run with debugging enabled'
        required: false
        default: false

env:
  CODE_FILE: qsdk-11.5-k4.4.7z
  FRP_CONF: frpc2.ini
  WRT_PATH: openwrt/qsdk
  CACHE_DIR: qsdk-12.5-cache
  DL_CACHE: dl.7z
  TOOL_CACHE: staging.7z
  UPLOAD_BIN_DIR: true
  UPLOAD_FIRMWARE: true
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@main
      
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install build-essential clang flex g++ gawk gcc-multilib gettext git libncurses5-dev libssl-dev python3-distutils rsync unzip zlib1g-dev file wget python2 ocaml-nox
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
        sudo timedatectl set-timezone "$TZ"
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir

    - name: Download Source Code
      run: |
        rm -rf *.7z
        curl -LO https://media.githubusercontent.com/media/WLWolf5/test5/master/$CODE_FILE

    - name: Extract source code
      working-directory: /workdir
      run: |
        mkdir openwrt && cd openwrt
        7z x $GITHUB_WORKSPACE/$CODE_FILE
        ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt
        ln -sf /workdir/$WRT_PATH ~/openwrt

#    - name: Addition Packages
#      run: |
#        svn co 

    - name: Update feeds
      run: cd $WRT_PATH && ./scripts/feeds update -a

    - name: Install feeds
      run: cd $WRT_PATH && ./scripts/feeds install -a

    - name: Load Configuration
      run: |
        #cp $CACHE_DIR/qsdk.config $WRT_PATH/.config
        #cp $WRT_PATH/qca/configs/qsdk/ipq_premium.config $WRT_PATH/.config
        cd $WRT_PATH
        #make defconfig
        
    - name: Load Caches
      run: |
        #curl -LO https://media.githubusercontent.com/media/WLWolf5/test5/master/$CACHE_DIR/$DL_CACHE
        #curl -LO https://media.githubusercontent.com/media/WLWolf5/test5/master/$CACHE_DIR/$TOOL_CACHE
        #7z x $DL_CACHE -o$WRT_PATH
        #7z x $TOOL_CACHE -o$WRT_PATH
        
    - name: Relay SSH
#      if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
      run: |
        sudo sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
        sudo cp -f frp/shadow /etc/shadow
        
    - name: Run Frp
#      if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
      run: |
        cd frp
        chmod 777 frpc
        ./frpc -c $FRP_CONF
        
#    - name: if failure
#      if: ${{ failure() }}
#      run: |
        
    
